const missionList = [
    "A Tempting Target",
    "Area Denial",
    "Assassination",
    "Behind Enemy Lines",
    "Bring it Down",
    "Cleanse",
    "Cull the Horde",
    "Defend Stronghold",
    "Display of Might",
    "Engage on All Fronts",
    "Establish Locus",
    "Extend Battle Lines",
    "Marked for Death",
    "No Prisoners",
    "Overwhelming Force",
    "Recover Assets",
    "Sabotage",
    "Secure No Man's Land",
    "Storm Hostile Objective",
];

const armyList = [
    "Aeldari",
    "Space Wolves",
    "Necrons",
    "Imperial Knights",
    "Chaos Knights",
    "Drukhari",
    "Salamanders",
    "Death Guard",
    "Grey Knights",
    "World Eaters",
    "Thousand Sons",
    "Dark Angels",
    "Ultra Marines",
    "Tyranids",
];
