const missionList = [
    "A Tempting Target",
    "Area Denial",
    "Assassination",
    "Behind Enemy Lines",
    "Bring it Down",
    "Cleanse",
    "Cull the Horde",
    "Defend Stronghold",
    "Display of Might",
    "Engage on All Fronts",
    "Establish Locus",
    "Extend Battle Lines",
    "Marked for Death",
    "No Prisoners",
    "Overwhelming Force",
    "Recover Assets",
    "Sabotage",
    "Secure No Man's Land",
    "Storm Hostile Objective",
];

const armyList = [
    "Aeldari",
    "Chaos Knights",
    "Dark Angels",
    "Death Guard",
    "Drukhari",
    "Grey Knights",
    "Imperial Knights",
    "Necrons",
    "Salamanders",
    "Space Wolves",
    "Thousand Sons",
    "Tyranids",
    "Ultra Marines",
    "World Eaters",
];
